### ISSUE TITLE
Import US ZCTA zipcode proxy geometries

### ISSUE THREAD

**Issue by riordan** [whosonfirst-data/whosonfirst-data-postalcode#8]
Census Bureau releases [ZIP Code Tabulation Area](http://www.census.gov/geo/reference/zctas.html) (ZCTA) as part of its yearly TIGER release.

They're not "real" polygons of postcodes (wah wah they're really routes), per se, but they basically serve as proxies.

Usually they're extracted from [TIGER/line](http://www.census.gov/geo/maps-data/data/tiger-line.html) data.

**Comment by thisisaaronland** [comment]
Blocked in issue #6

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/whosonfirst-sources/commit/24608c63faed2502ad5eed2ca7b262cd25e38299

https://github.com/whosonfirst-data/whosonfirst-data-postalcode-us/commit/72726dea5c6d4a3690e55dcd5c67090e30de98c8
