### ISSUE TITLE
Investigate postal code geometries from [VARIOUS SOURCES]

### ISSUE THREAD

**Issue by riordan** [whosonfirst-data/whosonfirst-data-postalcode#9]
CartoDB's [got geometries](https://github.com/CartoDB/data-services/tree/master/geocoder/postal-codes) from:
- US
- Canada
- France
- Australia

Worthy of an investigation?

```
Australian polygons - http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/2033.0.55.0012011?OpenDocument - Download the KMZ for Postal Area IRSD, SEIFA 2011. Unzip and upload the kmz
    Coverage: AUS
    Geometry type: polygon

Canadian polygons - http://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/bound-limit-2011-eng.cfm - Download ESRI Shp, Forward Sortation Areas, Digital Boundary
    Coverage: CAN
    Geometry type: polygon

USA polygons - http://www2.census.gov/geo/tiger/TIGER2013/ZCTA5/tl_2013_us_zcta510.zip
    Coverage: USA
    Geometry type: polygon

French polygons - http://www.data.gouv.fr/dataset/fond-de-carte-des-codes-postaux
    Coverage: FRA
    Geometry type: polygon
```

**Comment by thisisaaronland** [comment]
License(s) ?

**Comment by riordan** [comment]
- Aus - [CC-BY-2.5-AUS](http://creativecommons.org/licenses/by/2.5/au/) - _this was when porting required country-specific licenses_
- US - Public Domain
- Canada - [Statscan Unrestricted Use Agreement](http://www.statcan.gc.ca/pub/92-160-g/2011001/app-ann/app-anne-eng.htm)
- France [ODbL](http://www.data.gouv.fr/fr/datasets/fond-de-carte-des-codes-postaux/) _grumble_

**Comment by riordan** [comment]
Additional polygon datasets:
- [Netherlands](http://opendata.arcgis.com/datasets/ee6772a214fc4c13b8cd2993516e4417_1) - cc-by to ESRI Netherlands
- [Uruguay](https://catalogodatos.gub.uy/dataset/codigo-postal) - No license, but on an open data portal. Needs followup for clarification
- [Norway](http://data.norge.no/data/posten-norge/postnummer-i-norge) - [Norwegian License for Open Government Data](http://data.norge.no/nlod/en/1.0) - Attribution
- [Finland](http://tilastokeskus.fi/tup/paavo/index_en.html) - Retrieve via WFS - [Attribution license](http://www.stat.fi/org/lainsaadanto/yleiset_kayttoehdot_en.html)
  There may be more found by digging through [okfn](http://index.okfn.org/dataset/postcodes/)

**Comment by thisisaaronland** [comment]
@riordan Would you mind putting these links in to the issues for their respective country repos?
